version: '3'

services:
  db:
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: 'VikingWorld'
    container_name: VikingWorld
    volumes:
      - ./postgres:/var/lib/postgresql/data